### ISSUE TITLE
'stg show' chokes on unicode with python 2.6

### ISSUE THREAD

**Issue by awilliam** [ctmarinas/stgit#19]
$ python --version
Python 2.6.6
$ stg --version
Stacked GIT 0.18-101-g8fa6
git version 2.16.1
Python version 2.6.6 (r266:84292, Aug  9 2016, 06:11:56) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-17)]
$ stg show
Error: Unhandled exception:
Traceback (most recent call last):
  File "/home/alwillia/lib/python2.6/site-packages/stgit/main.py", line 194, in _main
    ret = command.func(parser, options, args)
  File "/home/alwillia/lib/python2.6/site-packages/stgit/commands/show.py", line 83, in func
    pager(commit_str)
  File "/usr/lib64/python2.6/pydoc.py", line 1312, in pager
    pager(text)
  File "/usr/lib64/python2.6/pydoc.py", line 1326, in <lambda>
    return lambda text: pipepager(text, os.environ['PAGER'])
  File "/usr/lib64/python2.6/pydoc.py", line 1353, in pipepager
    pipe.write(text)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf6' in position 75: ordinal not in range(128)

$ git show | head 
commit c7d12e277b834d4a05a7d3529e143780c8cfedb2
Author: Christian König <ckoenig.leichtzumerken@gmail.com>
Date:   Tue Jan 16 10:43:17 2018 +0100

    x86/PCI: apply the AMD window fixup on resume as well
    
    We need to reprogram the register content during resume.
    
    Signed-off-by: Christian König <christian.koenig@amd.com>
    Reported-by: Tom St Denis <tom.stdenis@amd.com>

This is a patch that recently generated an upstream lkml thread with Bjorn Helgaas and Linus Torvalds over the handling of unicode in stg imported commits.  The unicode appears to be handled correctly on import now and I can 'stg edit' the commit, but 'stg show' chokes on it.

**Comment by jpgrayson** [comment]
I have pushed a repair for this issue. @awilliam, if you could try it out and let me know if there are still any issues in your environment, that would be appreciated.

**Comment by awilliam** [comment]
Confirmed, works!  Thank you!
