### ISSUE TITLE
If pushing results in a conflict, do not immediately update the patch

### ISSUE THREAD

**Issue by hvdijk** [ctmarinas/stgit#27]
Test case:

    git init
    echo a > file && git add file && git commit -m a
    stg init
    stg new -m b b && echo b > file && stg refresh
    stg new -m c c && echo c > file && stg refresh
    stg pop b # pops c and b, pushes c

This is supposed to result in a conflict, and it does. However, it leaves me no option to leave the conflict to be resolved later. I should be able to do `git reset --hard && stg pop` and have a subsequent `stg push` re-create the conflict. This does not work because the attempted push of `c` already updated the patch: `git show` reveals that the patch is completely empty.

(Edit: `stg undo --hard` does work but does something else: that restores things to the state where b and c are both pushed.)

**Comment by jpgrayson** [comment]
Thank you for the test case and for writing this issue.

My first instinct for what might be better behavior would be for `stg undo --hard` to leave the stack in the state suggested:
```
- c
- b
```
One problem with this approach is that `undo` would no longer restore the stack to the state it was in before the last command (`stg pop b`) was issued and would instead leave the stack in an intermediate state that the user never achieved on her own. I'm not sure if it is a good idea for `stg undo` to leave the stack in a novel state like this.

> This is supposed to result in a conflict, and it does. However, it leaves me no option to leave the conflict to be resolved later.

Doing `stg undo --hard` and then, later, doing `stg pop b` again *does* give the option of resolving the conflict later. I appreciate that you want to both change the patch order *and* defer the conflict resolution, but I'm not sure how feasible that is from a commit consistency perspective.

It is perhaps interesting to consider that any way we try to change the order of `b` and `c` requires the conflicts of `c` to be resolved. I.e. the other way we might try to reorder `b` and `c`:
```
stg pop b c
stg push c  # same conflict, same stack state
```

At some level, we're asking that stgit be capable of pushing a patch onto the stack without having to deal with the consequences of that patch being applied to the working tree (i.e. conflicts). Again, I'm not sure that we want to soften this invariant of `stg push`.

I'm not entirely convinced that stgit needs any new or different behavior for this case, so I am interested in suggestions for how stgit might handle this situation better.

**Comment by hvdijk** [comment]
> I appreciate that you want to both change the patch order *and* defer the conflict resolution,

Actually, the primary goal of `stg pop b` was just to make sure `b` was not applied, as it had some unwanted effects. I wanted to keep later patches that applied cleanly, but anything that depended on `b`, that was less important than getting rid of `b`, so that was something to solve some other day. I'd be perfectly okay with keeping `c` in the patch series after `b`.

> Doing `stg undo --hard` and then, later, doing `stg pop b` again does give the option of resolving the conflict later.

That leaves `b` applied though. I simplified the scenario a bit to avoid cluttering the description with irrelevant details, but I had patches between `b` and `c` that were independent of `b` that were successfully reapplied. To get the result I was after, I'd need to `stg undo --hard`, then `stg pop -n <...>`, finally `stg push <patches>`. That seems like an overly complicated route just to undo one push attempt.

Thinking about how to implement this, I think I agree that there is probably no sane way for `stg push` and/or `stg pop` to handle this differently. Would adding an option to `stg undo` to allow undoing to an intermediate state (the state just before the attempt to push `c`) make sense?

**Comment by jpgrayson** [comment]
I'm wondering if specifying multiple patches to `stg pop` is a sufficient solution for this case?

If you know that `c` depends on `b`, then popping both at once is viable. Consider the scenario where `b` and `c` are interleaved between non-conflicting patches `x`, `y`, and `z` (does this better model your scenario?):

```
git init
echo a > file && git add file && git commit -m a
echo w > file2 && git add file2 && git commit -m w
stg init
stg new -m x && echo x > file2 && stg refresh
stg new -m b && echo b > file && stg refresh
stg new -m y && echo y > file2 && stg refresh
stg new -m c && echo c > file && stg refresh
stg new -m z && echo z > file2 && stg refresh
stg pop b c
```
This leaves us with:
```
stg series
+ x
+ y
> z
- b
- c
```
Mission accomplished?

If when we decide we want to pop `b`, we don't know which, if any, other patches depend on `b`, then we will still run into conflicts at which point we would still need to invoke `stg undo --hard`, but if there are relatively few patches that depend on `b`, then perhaps it's not so bad to iteratively add the dependent patches to the `stg pop` command. I.e.:

```
stg pop b
# merge conflict when applying `c`
stg undo --hard
stg pop b c
# merge conflict when applying `d`
stg undo --hard
stg pop b c d
# ok
```

It is conceivable to make stgit capable of the above iterative approach, but my feeling is that this capability would be too niche. Perhaps as a script in contrib?

```
#!/bin/sh

[ "$#" = 1 ] || { echo >&2 "Usage: $(basename $0) <patch>"; exit 1; }

patch="$1"
stg pop "$patch"
while [ "$?" = "3" ]; do
	patch="$patch $(stg top)"
	stg undo --hard
	stg pop $patch
done
```

**Comment by hvdijk** [comment]
`stg undo --hard` followed by `stg pop` with multiple patches is a good idea and would probably have worked well for my case, thank you for the suggestion! The script you wrote would only work if I use it every time instead of `stg pop`; I'm unlikely to remember that. I can probably tweak it to turn it into something that can be run after a failed `stg pop`, but it's going to become something that probably only works for me that way, not for anyone else.

Feel free to close this if there's no general improvement that you can think of that would help me as well as others.

**Comment by jpgrayson** [comment]
Closing. I do not have any changes in mind related to this issue.
