### ISSUE TITLE
stg rebase - remove empty patches?

### ISSUE THREAD

**Issue by jacobstanley** [ctmarinas/stgit#31]
Is there a way to get `stg rebase` to remove empty patches automatically?

The reason the patches are empty as they were merged upstream.

**Comment by lkraav** [comment]
Have you tried `stg rebase -m` yet?

**Comment by jacobstanley** [comment]
Ah I bet that would do it! Will try that next time :smile:

**Comment by lkraav** [comment]
I'm fairly certain this issue can be closed :+1:

**Comment by jpgrayson** [comment]
Closing under the assumption that `stg rebase -m; stg clean` is a sufficient workflow.
