### ISSUE TITLE
Very large commits break stgit on Windows

### ISSUE THREAD

**Issue by null77** [ctmarinas/stgit#44]
This has happened in a couple of repos. I made a very large commit with a number of files (e.g. deleting an entire repo) and then hang on `stg refresh`. Every other command on that branch is now broken, e.g. `stg push` or `stg delete -t`. Only reproduced on Windows right now.

**Comment by jpgrayson** [comment]
Hi @null77, thank you for opening this issue. And I'm sorry your stack is in a bad state.

Did you try using `stg undo` and/or `stg repair`? I'm curious whether your repo got into a state that those commands could not handle. What was the symptom you observed after the failed `refresh`?

---

Regarding the problematic `refresh`, my immediate suspicion is that stgit may have exhausted your system's memory while composing the patch metadata. The patch metadata is written to the `.stgit` branch, e.g. `master.stgit` to a `patches/<patchname>` file. The metadata contains references to bottom and top patches along with the author, date, and message. **AND** the diff is thrown in there for good measure.

It is the diff that I suspect is a problem when dealing with very large commits. In the case mentioned where a patch contains the removal of every file in a repository, `stg refresh` will read the diff output from `git diff-tree -M` _into memory_ and then write a blob containing the aforementioned patch metadata plus the diff. So when every file in the repo is removed, the diff that stgit reads into memory, manipulates, and rewrites will contain every line from the removed files with diff removal markers prepended.

The `git-diff-tree` manpage warns:

> The -M and -C options require O(n^2) processing time where n is the number of potential rename/copy targets.

So stgit may be consuming both copious amounts of memory _and_ CPU cycles trying to figure out if any of those removed files are really renamed.

---

So if the above hypothesis is correct (that the diff in the patch metadata is the core problem with large patches), then what can be done?

1. Omit diff from patch metadata. AFAICT, the diff in patch metadata is only useful as a human-readable reference. I.e. the diff is only visible to people trolling through the `patches/` directory in the `<branch>.stgit` branch. A quick test reveals that the test suite passes if this diff is omitted from the patch metadata files.
2. Reduce or limit the size of the diff. Using the `--break-rewrites` and `--irreversible-delete` options would be specifically helpful for large-scale remove/move/rewrite patches.
3. Reduce the amount of CPU time spent computing diffs. The `-l` option can be used to limit the `O(n^2)` explosion when lots of files are involved in the patch.

But before applying any of those potential solutions, the first order of business is to verify and quantify the effect of the patch metadata diff on `stg refresh`. A potential test case would be to start with the linux kernel repo and observe the effect of a large-scale removal of files. Measure CPU and memory consumption of `stg refresh` with and without the diff in the patch metadata.

**Comment by jpgrayson** [comment]
Ran a test against the repo where I refreshed a patch against `git rm -r Documentation`. There are 845957 lines across 6801 files in `Documentation`.

- Default refresh: 89.83s
- Refresh with `--irreversible-delete` diff: 1.15s
- Refresh with no diff in patch metadata: 0.67s
- Refresh with just diffstat in patch metadata: 0.97s

So this seems to confirm the hypothesis that the diff in the patch metadata can lead to very long `stg refresh` times.

My stance on this is that the diff in the patch metadata is for human consumption only, and thus we some discretion to apply regarding whether and how much diff information goes into the patch metadata. So some options:

* Omit diff entirely
* Limit diff size with `--irreversible-delete`, etc.
* Only show diff stat.
* Use a heuristic to determine how much diff can be afforded.
  * Small patch: full diff in patch metadata
  * Medium patch: regular diff stat in patch metadata
  * Huge patch: `--shortstat` only in patch metadata

I'm not feeling particularly motivated to take on the heuristic based approach (too many tests to write), so I'm leaning toward "only show diff stat" as a middle ground that keeps refresh time and repo size small while still providing useful information to users regarding the content of the patch.

**Comment by null77** [comment]
Hey Pete. Sorry I haven't had a chance to respond yet. I don't recall if `stg undo` worked. `stg pop` and similar commands all hung. The only thing that seemed to work for me was to delete the branch and start over. As far as a fix goes anything to get the branch into a working state after this lock up would be sufficient.

**Comment by jpgrayson** [comment]
Hi @null77, I have pushed a change that has a positive effect on this problem and, I am hoping, fully resolves what you have observed on Windows.

It would be helpful for me if you could retry one of the troublesome scenarios with this change. I have measured significant (order of magnitude) improvement in `stg refresh` runtime on large-diff patches, but I do not have a Windows environment at my disposal and I am not certain that Windows' poor small file IO is not the dominant factor on that platform.

**Comment by jpgrayson** [comment]
StGit no longer puts either diff or diffstat information into the per-patch metadata files. My belief is that this fully alleviates the kind of pathological effects of huge patches that are mentioned in this issue. Closing until someone barks again.
