### ISSUE TITLE
patchdescr.tmpl template file is ignored by "stg new" command

### ISSUE THREAD

**Issue by pschiffe** [ctmarinas/stgit#9]
Hello, there was a bug reported on the previous site of stgit [1] about $title. The patch can be found in the wayback machine. Would you consider to accept that patch? I'm writing because we are carrying that patch in Fedora as some people are using that feature [2]. Thanks.

[1] https://web.archive.org/web/20170205225257/https://gna.org/bugs/?20349
[2] https://bugzilla.redhat.com/show_bug.cgi?id=872651

**Comment by ctmarinas** [comment]
Ah, this was missed with the new infrastructure. Happy to apply it. Do you happen to know who the original author was?

**Comment by pschiffe** [comment]
Sorry, I don't know. Thank you.

**Comment by terinjokes** [comment]
I'm now also applying the Fedora patch in the Arch Linux AUR package.

https://aur.archlinux.org/packages/stgit/
